[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "autopep8",
    "bcrypt",
    "beautifulsoup4>=4.13.4",
    "fastapi>=0.116.1",
    "numpy>=1.24.0",
    "opencv-python>=4.8.0",
    "openai>=1.100.2",
    "pillow>=10.0.0",
    "psycopg2-binary",
    "pyjwt",
    "python-dotenv",
    "requests>=2.32.5",
    "schedule",
    "scikit-learn>=1.3.0",
    "sqlalchemy",
    "uvicorn>=0.35.0",
    "replit-object-storage>=1.0.2",
]
