[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "autopep8",
    "bcrypt",
    "beautifulsoup4>=4.13.4",
    "fastapi>=0.116.1",
    "openai>=1.100.2",
    "psycopg2-binary",
    "pyjwt",
    "python-dotenv",
    "requests>=2.32.5",
    "schedule",
    "sqlalchemy",
    "uvicorn>=0.35.0",
]
