[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "skyy-rose-ai-agents"
version = "3.0.0"
description = "Luxury Streetwear AI Agent Management Platform with GOD MODE Level 2"
readme = "README.md"
authors = [
    {name = "Skyy Rose Co", email = "admin@skyyrose.co"}
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Office/Business",
    "Topic :: Artistic Software",
]
requires-python = ">=3.11"
# Truth Protocol Compliance: All versions pinned exactly per CLAUDE.md requirements
# References requirements.txt as single source of truth for production dependencies
dependencies = [
    # Core Framework - Versions per PEP 440, pinned for reproducibility
    "fastapi==0.119.0",           # FastAPI web framework
    "uvicorn[standard]==0.34.0",  # ASGI server
    "python-dotenv==1.0.1",       # Environment configuration
    "pydantic==2.7.4",            # Data validation (langchain compatibility >=2.7.4)
    "starlette==0.48.0",          # FastAPI dependency

    # HTTP & API
    "requests==2.32.4",           # HTTP client (GHSA-9hjg-9r4m-mvj7 fixed)
    "python-multipart==0.0.18",   # Form data parsing
    "aiofiles==24.1.0",           # Async file operations
    "httpx==0.28.1",              # Async HTTP client

    # Database - SQLAlchemy (primary), MongoDB support via Motor
    "SQLAlchemy==2.0.36",         # ORM framework
    "aiosqlite==0.20.0",          # Async SQLite driver
    "asyncpg==0.30.0",            # Async PostgreSQL driver
    "pymongo==4.10.1",            # MongoDB driver (legacy support)
    "motor==3.6.0",               # Async MongoDB driver
    "dnspython==2.7.0",           # DNS resolution for MongoDB

    # Authentication & Security - RFC 7519 (JWT), NIST SP 800-132 (PBKDF2), OWASP guidance
    "PyJWT==2.10.1",              # RFC 7519 JWT implementation (replaces python-jose)
    "passlib[bcrypt]==1.7.4",     # Password hashing per OWASP
    "bcrypt==4.2.1",              # Bcrypt algorithm (fallback)
    "argon2-cffi==23.1.0",        # Argon2id per OWASP 2023 recommendations (primary)
    "cryptography==46.0.2",       # NIST SP 800-38D AES-GCM, multiple CVE fixes
    "certifi==2024.12.14",        # CA certificates
    "paramiko==3.5.0",            # SSH client

    # Security Middleware
    "slowapi==0.1.9",             # Rate limiting
    "secure==0.3.0",              # Security headers

    # AI & ML
    "anthropic==0.69.0",          # Claude AI
    "openai==2.3.0",              # OpenAI API
]

[project.optional-dependencies]
dev = [
    # Development & Testing - Pinned versions per Truth Protocol
    "pytest==8.3.4",
    "pytest-asyncio==0.24.0",
    "pytest-cov==6.0.0",
    "black==24.10.0",
    "flake8==7.1.1",
    "mypy==1.13.0",
    "isort==5.13.2",
    "bandit==1.8.0",              # Security linting
    "safety==3.2.11",             # Vulnerability scanning
    "pip-audit==2.8.0",           # Dependency audit
]

[project.urls]
Homepage = "https://skyyrose.co"
Repository = "https://github.com/skyy-rose/ai-agents"
Documentation = "https://docs.skyyrose.co"

[project.scripts]
skyy-agents = "main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["agent*", "backend*"]
exclude = ["tests*", "frontend*"]

[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | frontend
)/
'''

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob = ["frontend/*", "build/*", "dist/*"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true