"""CI gate — surface compositor-blocking SKUs in the source-photo manifest.

Reads the manifest at
``assets/products/source-photos/manifest.json`` (regenerated by
``scripts/audit_source_photos.py``) and reports every active SKU that lacks
the minimum angles (front + back) the compositor needs.

This test is INFORMATIONAL by default — it prints the blocked list as a
warning so CI logs surface it, but does NOT fail the build (per the resolved
scope decision: techflats can stand in temporarily). To promote to a hard
gate after sourcing completes, flip ``ENFORCE_MINIMUM_COVERAGE`` to True.
"""

from __future__ import annotations

import json
import warnings
from dataclasses import asdict
from pathlib import Path

import pytest

from tests.sparse_guard import requires_tree

ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = ROOT / "assets" / "products" / "source-photos" / "manifest.json"

# Every test reads the manifest under assets/ — sparse worktrees exclude that
# tree by design; full checkouts and CI still fail closed on a missing manifest.
pytestmark = requires_tree("assets/products/source-photos")

# Promote to True after every active SKU has at least front + back. Until then,
# the warning surfaces gaps without blocking the build.
ENFORCE_MINIMUM_COVERAGE = False


def test_manifest_exists():
    assert (
        MANIFEST_PATH.exists()
    ), "assets/products/source-photos/manifest.json missing — run `python scripts/audit_source_photos.py` first."


def test_manifest_schema():
    """Manifest top-level shape sanity check."""
    data = json.loads(MANIFEST_PATH.read_text())
    assert "version" in data
    assert "required_angles_by_garment_type" in data
    assert "minimum_for_compositor" in data
    assert "summary" in data
    assert "skus" in data
    assert isinstance(data["skus"], dict)
    assert len(data["skus"]) >= 30, f"expected ≥30 active SKUs in manifest, got {len(data['skus'])}"


def test_committed_manifest_matches_full_regeneration():
    """Every generated byte of 33-SKU coverage must match current authorities."""
    from scripts import audit_source_photos as audit

    committed = json.loads(MANIFEST_PATH.read_text())
    regenerated, _ = audit.build_manifest()
    assert committed == regenerated


def test_generated_reports_match_full_regeneration():
    from scripts import audit_source_photos as audit

    manifest, coverages = audit.build_manifest()
    assert audit.AUDIT_PATH.read_text() == audit._render_audit_md(coverages, manifest["summary"])
    assert audit.SHOOT_LIST_PATH.read_text() == audit._render_shoot_list_md(coverages)


def test_catalog_garment_types_normalize_for_every_sku():
    from scripts import audit_source_photos as audit
    from skyyrose.core.catalog_loader import read_catalog_rows

    manifest, _ = audit.build_manifest()
    rows = [row for row in read_catalog_rows() if row.get("sku")]
    assert set(manifest["skus"]) == {row["sku"] for row in rows}
    assert manifest["skus"]["sg-002"]["garment_type"] == "tee"
    assert manifest["skus"]["lh-004"]["garment_type"] == "jacket"
    assert manifest["skus"]["sg-014"]["garment_type"] == "joggers"
    assert all(
        entry["garment_type"] in audit.REQUIRED_ANGLES_BY_TYPE
        for entry in manifest["skus"].values()
    )


def test_scan_is_deterministic_and_collision_safe():
    from scripts import audit_source_photos as audit

    assert audit._scan_files() == audit._scan_files()
    preferred = audit._PhotoCandidate(ROOT / "preferred.jpg", (0, 0, 1))
    fallback = audit._PhotoCandidate(ROOT / "fallback.jpg", (1, 0, 1))
    assert audit._select_candidate("x-001", "front", [fallback, preferred]) == preferred.path

    collision = audit._PhotoCandidate(ROOT / "collision.jpg", preferred.priority)
    with pytest.raises(audit.PhotoCollisionError, match="same-priority"):
        audit._select_candidate("x-001", "front", [collision, preferred])


def test_br007_preserves_directional_side_authority():
    """BR-007's two side panels must never collapse into one ambiguous view."""
    from scripts import audit_source_photos as audit
    from skyyrose.core.catalog_loader import read_catalog_rows

    row = next(row for row in read_catalog_rows() if row.get("sku") == "br-007")
    generated = asdict(audit._build_coverage_for(row, audit._scan_files()["br-007"]))
    coverage = json.loads(MANIFEST_PATH.read_text())["skus"]["br-007"]

    assert coverage == generated

    assert coverage["garment_type"] == "shorts"
    assert coverage["photo_paths"]["wearer-left"].endswith("br-007-shorts-wearer-left.jpeg")
    assert coverage["photo_paths"]["wearer-right"].endswith("br-007-shorts-wearer-right.jpeg")
    assert coverage["photo_paths"]["founder-four-angle"].endswith(
        "br-007-founder-four-angle-physical-authority.jpg"
    )
    assert "side" in coverage["present_angles"]


def test_founder_four_angle_board_cannot_replace_individual_view_authority():
    """The proof board is supplemental and cannot satisfy compositor angles alone."""
    from scripts import audit_source_photos as audit
    from skyyrose.core.catalog_loader import read_catalog_rows

    row = next(row for row in read_catalog_rows() if row.get("sku") == "br-007")
    board = (
        ROOT
        / "assets/products/source-photos/black-rose"
        / "br-007-founder-four-angle-physical-authority.jpg"
    )
    coverage = asdict(audit._build_coverage_for(row, {"founder-four-angle": board}))

    assert coverage["present_angles"] == []
    assert coverage["missing_angles"] == ["front", "back", "side", "detail-pocket"]
    assert coverage["has_minimum_for_compositor"] is False


def test_source_photo_cli_uses_wearer_relative_angles():
    from scripts import source_product_photos

    assert "wearer-left" in source_product_photos._VALID_ANGLES
    assert "wearer-right" in source_product_photos._VALID_ANGLES
    assert "left-side" not in source_product_photos._VALID_ANGLES
    assert "right-side" not in source_product_photos._VALID_ANGLES
    assert "side" not in source_product_photos._VALID_ANGLES


def test_minimum_compositor_coverage():
    """Surface any SKUs missing front+back. WARN by default; FAIL if enforced."""
    data = json.loads(MANIFEST_PATH.read_text())
    blocked = [
        sku for sku, c in data["skus"].items() if not c.get("has_minimum_for_compositor", False)
    ]
    if blocked:
        msg = (
            f"{len(blocked)}/{len(data['skus'])} SKUs lack front+back source "
            f"photography (compositor-blocked): {', '.join(sorted(blocked))}"
        )
        if ENFORCE_MINIMUM_COVERAGE:
            pytest.fail(msg)
        warnings.warn(msg, UserWarning, stacklevel=1)


@pytest.mark.parametrize(
    "garment_type",
    [
        "tee",
        "hoodie",
        "crewneck",
        "jersey",
        "shorts",
        "joggers",
        "set",
        "jacket",
        "accessory",
    ],
)
def test_required_angles_defined_for_each_garment_type(garment_type):
    """Every garment type the inferrer can emit must have a required-angles list."""
    data = json.loads(MANIFEST_PATH.read_text())
    required = data["required_angles_by_garment_type"]
    assert (
        garment_type in required
    ), f"manifest missing required_angles for garment type {garment_type!r}"
    assert (
        len(required[garment_type]) >= 2
    ), f"{garment_type}: required angles list too short ({required[garment_type]})"
