"""Build full-frame delivery copies; approved 640w originals retain authority."""

import argparse
import hashlib
import io
import json
import os
import tempfile
from pathlib import Path

import PIL
from PIL import Image, ImageChops, features

THEME = Path(__file__).resolve().parents[2] / "wordpress-theme/skyyrose-flagship-2"
OUTPUT = "assets/derived/card-frames"
WIDTH = 384
# Independent review accepted this full-frame recipe at 358 CSS pixels/DPR1.
QUALITY = 80
SOURCES = {
    "signature": ("554c2372bc1a9cf61aefd5782b9792db26522698ee8e860ae2befcde9302857d", 640, 1070),
    "black-rose": ("37809df50e66216e624742ee1addf0fff822509fcd8951e1483af273bf50bd9d", 640, 1068),
    "love-hurts": ("d3294b315a023ce6d9fadd0a9b87742f00749200b2efa3ba1ce87fab43eca190", 640, 1075),
    "kids-capsule": ("99480ca73a7d1fe7e0b7a0d2ac891b523fcdb8f1101a5210ec764e9414cb8cc9", 640, 1068),
}


def digest(raw: bytes) -> str:
    """Hash exact source or generated bytes."""
    return hashlib.sha256(raw).hexdigest()


def safe_path(relative: str) -> Path:
    """Reject traversal and symlinks at every existing path component."""
    name = Path(relative)
    if name.is_absolute() or ".." in name.parts or not name.parts:
        raise ValueError("Unsafe delivery path")
    destination = THEME / name
    for entry in (destination, *destination.parents):
        if entry.is_symlink():
            raise ValueError(f"Symlink delivery path: {entry}")
    destination.resolve().relative_to(THEME.resolve())
    return destination


def validate_decoded(payload: bytes, resized: Image.Image, metadata: dict) -> None:
    """Require full dimensions and lossless alpha after lossy RGB encoding."""
    with Image.open(io.BytesIO(payload)) as decoded:
        decoded.load()
        if decoded.mode != "RGBA" or decoded.size != resized.size:
            raise ValueError("Generated dimensions or alpha mode changed")
        if ImageChops.difference(decoded.getchannel("A"), resized.getchannel("A")).getextrema() != (
            0,
            0,
        ):
            raise ValueError("Generated alpha differs from resized source")
        if any(decoded.info.get(key) != value for key, value in metadata.items()):
            raise ValueError("Generated metadata changed")


def derive(raw: bytes, expected: tuple, width: int | None = None) -> tuple[bytes, int]:
    """Generate exactly one pinned-codec, uncropped technical rendition."""
    width = WIDTH if width is None else width
    if PIL.__version__ != "12.3.0" or features.version("webp") != "1.6.0":
        raise ValueError("Unpinned Pillow/libwebp generator")
    if digest(raw) != expected[0]:
        raise ValueError("Approved frame source drift")
    with Image.open(io.BytesIO(raw)) as original:
        original.load()
        if original.size != expected[1:] or original.mode != "RGBA":
            raise ValueError("Approved frame dimensions or mode changed")
        if original.getexif().get(274, 1) != 1:
            raise ValueError("Unexpected source orientation")
        metadata = {
            key: original.info[key]
            for key in ("icc_profile", "exif", "xmp")
            if key in original.info
        }
        height = round(original.height * width / original.width)
        resized = original.resize((width, height), Image.Resampling.LANCZOS)
        stream = io.BytesIO()
        resized.save(stream, "WEBP", quality=QUALITY, method=6, exact=True, **metadata)
        payload = stream.getvalue()
        validate_decoded(payload, resized, metadata)
        return payload, height


def write_atomic(relative: str, payload: bytes) -> None:
    """Atomically replace only the validated generated destination."""
    destination = safe_path(relative)
    destination.parent.mkdir(parents=True, exist_ok=True)
    safe_path(relative)
    with tempfile.NamedTemporaryFile(dir=destination.parent, delete=False) as stream:
        temporary = Path(stream.name)
        stream.write(payload)
    try:
        safe_path(relative)
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)


def generate(check: bool = False) -> dict:
    """Preflight all inputs/outputs before writing; check mode never writes."""
    safe_path(OUTPUT)
    pending = {}
    manifest = {
        "schema": "skyyrose.frame-delivery.v1",
        "recipe": {
            "pillow": "12.3.0",
            "libwebp": "1.6.0",
            "width": WIDTH,
            "quality": QUALITY,
            "method": 6,
            "exact": True,
            "resampling": "LANCZOS",
        },
        "collections": {},
    }
    for slug, expected in sorted(SOURCES.items()):
        if not slug or any(char not in "abcdefghijklmnopqrstuvwxyz-" for char in slug):
            raise ValueError("Invalid collection key")
        source = f"assets/sot/images/product-card-portals/{slug}-portal-statue-640w.webp"
        raw = safe_path(source).read_bytes()
        payload, height = derive(raw, expected)
        target = f"{OUTPUT}/{slug}-{WIDTH}w.webp"
        safe_path(target)
        pending[target] = payload
        manifest["collections"][slug] = {
            "source": source,
            "source_sha256": expected[0],
            "source_width": expected[1],
            "source_height": expected[2],
            "rendition": {
                "src": target,
                "width": WIDTH,
                "height": height,
                "sha256": digest(payload),
                "bytes": len(payload),
                "alpha_exact": True,
            },
        }
        # A closer 360w source avoids overdelivery at the 358px mobile slot.
        # Keep 384w and the original 640w choices for every larger requirement.
        if WIDTH > 360:
            narrow, narrow_height = derive(raw, expected, 360)
            narrow_target = f"{OUTPUT}/{slug}-360w.webp"
            safe_path(narrow_target)
            pending[narrow_target] = narrow
            manifest["collections"][slug]["narrow_rendition"] = {
                "src": narrow_target,
                "width": 360,
                "height": narrow_height,
                "sha256": digest(narrow),
                "bytes": len(narrow),
                "alpha_exact": True,
            }
    manifest_path = f"{OUTPUT}/manifest.json"
    safe_path(manifest_path)
    pending[manifest_path] = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode()
    for relative, payload in pending.items():
        destination = safe_path(relative)
        if check:
            if not destination.is_file() or destination.read_bytes() != payload:
                raise ValueError(f"Stale frame delivery: {relative}")
        else:
            write_atomic(relative, payload)
    return manifest


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    result = generate(arguments.check)
    print(
        f"{'Verified' if arguments.check else 'Built'} {len(result['collections'])} frame copies; originals unchanged"
    )
