<?php
/**
 * Product catalog and WooCommerce reconciliation.
 *
 * Extracted from the flagship production architecture so V2 keeps commerce
 * concerns modular while retaining its SOT-first, skyyrose2-prefixed API.
 *
 * @package SkyyRoseFlagship2
 */

defined( 'ABSPATH' ) || exit;

/** @return int Live cart count without assuming WooCommerce is active. */
function skyyrose2_cart_count() {
	return function_exists( 'WC' ) && WC()->cart ? WC()->cart->get_cart_contents_count() : 0;
}

/**
 * Return the catalog-derived V2 product-presentation registry.
 *
 * The JSON artifact is generated by scripts/build-product-presentation-registry.py
 * from the canonical catalog CSV plus the explicit Jersey Series supplement.
 * It intentionally contains no Woo IDs, prices, stock, or media bytes: those
 * remain live WooCommerce/SOT authorities.
 *
 * @return array<string,mixed>
 */
function skyyrose2_presentation_registry() {
	static $registry = null;
	if ( null !== $registry ) {
		return $registry;
	}

	$path = SKYYROSE2_DIR . '/data/product-presentation-registry.json';
	if ( ! is_readable( $path ) ) {
		$registry = array();
		return $registry;
	}

	$decoded  = json_decode( file_get_contents( $path ), true ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
	$registry = is_array( $decoded ) ? $decoded : array();
	return $registry;
}

/** @param WC_Product $product @return array<string,mixed> */
function skyyrose2_product_presentation( $product ) {
	$sku      = $product && method_exists( $product, 'get_sku' ) ? sanitize_key( $product->get_sku() ) : '';
	$registry = skyyrose2_presentation_registry();
	$records  = isset( $registry['products'] ) && is_array( $registry['products'] ) ? $registry['products'] : array();
	return $sku && isset( $records[ $sku ] ) && is_array( $records[ $sku ] ) ? $records[ $sku ] : array();
}

/**
 * Compare the published WooCommerce SKU surface with the presentation SOT.
 *
 * The presentation registry intentionally does not own WooCommerce facts, but
 * a missing record must be visible to an operator instead of disappearing from
 * an editorial rail without explanation. This report is admin-only and is
 * cached for the current request so storefront rendering stays fail-closed.
 *
 * @return array{missing:array<int,string>,extra:array<int,string>}
 */
function skyyrose2_registry_reconciliation_report() {
	static $report = null;
	if ( null !== $report ) {
		return $report;
	}

	$report = array(
		'missing'             => array(),
		'extra'               => array(),
		'collection_mismatch' => array(),
	);
	if ( ! function_exists( 'wc_get_products' ) ) {
		return $report;
	}

	$registry = skyyrose2_presentation_registry();
	$records  = isset( $registry['products'] ) && is_array( $registry['products'] ) ? $registry['products'] : array();
	$live     = array();
	$products = wc_get_products(
		array(
			'limit'   => -1,
			'status'  => 'publish',
			'orderby' => 'ID',
			'order'   => 'ASC',
		)
	);
	foreach ( $products as $product ) {
		if ( ! is_object( $product ) || ! method_exists( $product, 'get_sku' ) ) {
			continue;
		}
		$sku = sanitize_key( $product->get_sku() );
		if ( $sku ) {
			$live[ $sku ] = true;
			$record       = isset( $records[ $sku ] ) && is_array( $records[ $sku ] ) ? $records[ $sku ] : array();
			$expected     = ! empty( $record['collection'] ) ? sanitize_title( $record['collection'] ) : '';
			if ( $expected && function_exists( 'has_term' ) && ! has_term( $expected, 'product_cat', $product->get_id() ) ) {
				$report['collection_mismatch'][] = sprintf( '%s (registry: %s)', $sku, $expected );
			}
		}
	}

	$registry_skus = array_fill_keys( array_map( 'sanitize_key', array_keys( $records ) ), true );
	$report['missing'] = array_values( array_diff( array_keys( $live ), array_keys( $registry_skus ) ) );
	$report['extra']   = array_values( array_diff( array_keys( $registry_skus ), array_keys( $live ) ) );
	sort( $report['missing'] );
	sort( $report['extra'] );
	sort( $report['collection_mismatch'] );
	return $report;
}

/** Surface catalog drift to administrators without changing storefront output. */
function skyyrose2_registry_reconciliation_notice() {
	if ( ! is_admin() || ! current_user_can( 'manage_woocommerce' ) ) {
		return;
	}
	$report = skyyrose2_registry_reconciliation_report();
	if ( empty( $report['missing'] ) && empty( $report['extra'] ) && empty( $report['collection_mismatch'] ) ) {
		return;
	}
	$parts = array();
	if ( ! empty( $report['missing'] ) ) {
		$parts[] = sprintf( __( 'published WooCommerce SKUs missing from the V2 presentation registry: %s', 'skyyrose-flagship-2' ), implode( ', ', $report['missing'] ) );
	}
	if ( ! empty( $report['extra'] ) ) {
		$parts[] = sprintf( __( 'registry SKUs not currently published in WooCommerce: %s', 'skyyrose-flagship-2' ), implode( ', ', $report['extra'] ) );
	}
	if ( ! empty( $report['collection_mismatch'] ) ) {
		$parts[] = sprintf( __( 'products whose WooCommerce collection category disagrees with the V2 registry: %s', 'skyyrose-flagship-2' ), implode( ', ', $report['collection_mismatch'] ) );
	}
	printf( '<div class="notice notice-warning"><p><strong>%s</strong> %s</p></div>', esc_html__( 'SkyyRose V2 catalog drift detected.', 'skyyrose-flagship-2' ), esc_html( implode( ' ', $parts ) ) );
}
add_action( 'admin_notices', 'skyyrose2_registry_reconciliation_notice' );

/** @param WC_Product $product @return bool */
function skyyrose2_is_preorder_product( $product ) {
	$presentation = skyyrose2_product_presentation( $product );
	return ! empty( $presentation['is_preorder'] );
}

/**
 * Query published products for reusable marketplace sections.
 *
 * @param int    $limit Product limit.
 * @param string $collection Product category slug.
 * @param bool   $featured Featured-only query.
 * @return array<int,WC_Product>
 */
function skyyrose2_get_products( $limit = 6, $collection = '', $featured = false ) {
	if ( ! function_exists( 'wc_get_products' ) ) {
		return array();
	}
	$args = array(
		/*
		 * A narrow query can be filled by Jersey Series products before the
		 * presentation guard excludes them from the core Black Rose rail.
		 * Resolve against the full published collection, then apply the display
		 * limit after registry/presentation isolation has succeeded.
		 */
		'limit'   => -1,
		'status'  => 'publish',
		'orderby' => 'date',
		'order'   => 'DESC',
	);
	if ( $collection && 'pre-order' !== $collection ) {
		$args['category'] = array( sanitize_title( $collection ) );
	}
	if ( $featured ) {
		$args['featured'] = true;
	}
	$products = wc_get_products( $args );
	$filtered = array();
	foreach ( $products as $product ) {
		$presentation = skyyrose2_product_presentation( $product );
		if ( empty( $presentation ) ) {
			continue;
		}
		if ( $collection && 'pre-order' !== $collection && sanitize_title( $presentation['collection'] ?? '' ) !== sanitize_title( $collection ) ) {
			continue;
		}
		if ( 'pre-order' === $collection && empty( $presentation['is_preorder'] ) ) {
			continue;
		}
		if ( 'black-rose' === $collection && 'jersey-series' === ( $presentation['presentation'] ?? '' ) ) {
			continue;
		}
		$filtered[] = $product;
		if ( count( $filtered ) >= absint( $limit ) ) {
			break;
		}
	}
	return $filtered;
}

/**
 * Resolve the garment proof assigned to a Scroll World chapter.
 *
 * A chapter remains scenic, but it must also carry a real item from its own
 * collection. The product image, name, price, and availability stay WooCommerce
 * authoritative; Jersey Series remains isolated from the core Black Rose rail.
 *
 * @param string $collection Collection slug.
 * @param int    $chapter Chapter index.
 * @return WC_Product|false
 */
function skyyrose2_collection_scene_product( $collection, $chapter = 0 ) {
	$products = skyyrose2_get_products( 12, $collection );
	if ( empty( $products ) ) {
		return false;
	}
	$index = absint( $chapter ) % count( $products );
	return $products[ $index ] ?? false;
}

/**
 * Resolve a fixed product cast by exact SKU and collection membership.
 *
 * This is deliberately stricter than a product query: Royal Procession roles
 * must never swap, approximate, or inherit a product from another collection.
 * WooCommerce remains the authority for publication, visibility, price,
 * availability, variations, and the product URL.
 *
 * @param array<int,string> $skus Exact SKU identifiers in required order.
 * @param string            $required_collection Required product-category slug.
 * @return array<string,WC_Product> Products keyed by normalized SKU.
 */
function skyyrose2_get_products_by_skus( $skus, $required_collection ) {
	if ( ! function_exists( 'wc_get_product_id_by_sku' ) || ! function_exists( 'wc_get_product' ) ) {
		return array();
	}

	$required_collection = sanitize_title( $required_collection );
	$products            = array();
	foreach ( array_unique( array_map( 'sanitize_key', $skus ) ) as $sku ) {
		$product_id = absint( wc_get_product_id_by_sku( $sku ) );
		$product    = $product_id ? wc_get_product( $product_id ) : false;
		if ( ! $product || ! $product->is_visible() ) {
			continue;
		}
		if ( function_exists( 'get_post_status' ) && 'publish' !== get_post_status( $product_id ) ) {
			continue;
		}

		$collection_slugs = wp_get_post_terms( $product_id, 'product_cat', array( 'fields' => 'slugs' ) );
		if ( is_wp_error( $collection_slugs ) || ! in_array( $required_collection, $collection_slugs, true ) ) {
			continue;
		}
		$presentation = skyyrose2_product_presentation( $product );
		if ( empty( $presentation ) || sanitize_title( $presentation['collection'] ?? '' ) !== $required_collection ) {
			continue;
		}

		$resolved_sku = sanitize_key( $product->get_sku() );
		if ( $resolved_sku !== $sku ) {
			continue;
		}
		$products[ $sku ] = $product;
	}

	return $products;
}

/**
 * Render product cards with WooCommerce as product truth.
 *
 * @param int    $limit Product limit.
 * @param string $collection Category slug.
 * @param bool   $featured Featured-only query.
 */
function skyyrose2_product_cards( $limit = 6, $collection = '', $featured = false ) {
	$products = skyyrose2_get_products( $limit, $collection, $featured );
	if ( empty( $products ) && $featured ) {
		$products = skyyrose2_get_products( $limit, $collection, false );
	}
	if ( empty( $products ) ) {
		echo '<p class="sr2-empty">' . esc_html__( 'Next pieces entering the world soon.', 'skyyrose-flagship-2' ) . '</p>';
		return;
	}
	?>
	<div class="sr2-products sr2-products--prototype">
		<?php foreach ( $products as $index => $product ) : ?>
			<?php skyyrose2_render_product_loop_card( $product, $index ); ?>
		<?php endforeach; ?>
	</div>
	<?php
}

/**
 * Return the declared collection-world frames used by an individual product
 * reel. The frames are environment/art direction only; WooCommerce product
 * media remains the garment proof and transaction authority.
 *
 * @param array<string,mixed>|null $collection_data Current collection data.
 * @return array<int,array<string,string>>
 */
function skyyrose2_product_card_reel_frames( $collection_data ) {
	if ( empty( $collection_data['world'] ) || ! is_array( $collection_data['world'] ) ) {
		return array();
	}

	$frames = array();
	foreach ( array_slice( $collection_data['world'], 0, 3 ) as $scene ) {
		$uri = skyyrose2_collection_scene_uri( $scene );
		if ( ! $uri ) {
			continue;
		}
		$frames[] = array(
			'uri'   => $uri,
			'label' => isset( $scene['label'] ) ? $scene['label'] : '',
			'copy'  => isset( $scene['copy'] ) ? $scene['copy'] : '',
		);
	}
	return $frames;
}
