name: Vercel Integration Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  vercel-preview:
    name: Vercel Preview Deployment
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      - name: 'Notify Vercel - Preview Status'
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
          name: 'Vercel - dev-skyy: preview'
        if: always()

  vercel-production:
    name: Vercel Production Deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: 'Notify Vercel - Production Status'
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
          name: 'Vercel - dev-skyy: production'
        if: always()

  status-check:
    name: Vercel Status Check
    runs-on: ubuntu-latest
    needs: [vercel-preview, vercel-production]
    if: always()
    
    steps:
      - name: 'Notify Vercel - Overall Status'
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
          name: 'Vercel - dev-skyy: complete'
        if: always()
